AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - 'blogify.gemspec'
    - 'app/helpers/blogify/seo_helper.rb'
    - 'app/helpers/blogify/featured_image_helper.rb'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'app/helpers/blogify/seo_helper.rb'
    - 'app/services/blogify/seo_schema_generator.rb'
    - 'app/helpers/blogify/featured_image_helper.rb'

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/helpers/blogify/seo_helper.rb'
    - 'app/services/blogify/seo_schema_generator.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/helpers/blogify/seo_helper.rb'
    - 'app/services/blogify/seo_schema_generator.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'lib/blogify/configuration.rb'
    - 'app/helpers/blogify/seo_helper.rb'
    - 'app/helpers/blogify/featured_image_helper.rb'
    - 'app/services/blogify/seo_schema_generator.rb'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: false

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'app/helpers/blogify/seo_helper.rb'

Lint/DuplicateBranch:
  Exclude:
    - 'app/helpers/blogify/featured_image_helper.rb'
    - 'app/services/blogify/seo_schema_generator.rb'
